# Generated by Django 3.2.3 on 2021-10-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsreservationhistory',
            name='day1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carsreservationhistory',
            name='day2',
            field=models.DateField(),
        ),
    ]
