# Generated by Django 3.2.3 on 2021-10-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211014_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_started', models.DateTimeField()),
                ('day_ended', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carevent'),
        ),
    ]
