# Generated by Django 3.2.3 on 2021-10-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_daily_rental_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
    ]
