# Generated by Django 3.2.3 on 2021-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211016_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsreservationhistory',
            name='day1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='carsreservationhistory',
            name='day2',
            field=models.DateTimeField(),
        ),
    ]
