# Generated by Django 3.2.3 on 2021-10-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_order_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
