# Generated by Django 3.2.3 on 2021-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_ended',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
