# Generated by Django 3.2.3 on 2021-09-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210907_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_ended',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_ended',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_started',
            field=models.DateField(),
        ),
    ]
