# Generated by Django 3.2.3 on 2021-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210908_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_ended',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_started',
            field=models.DateTimeField(),
        ),
    ]
