# Generated by Django 3.2.3 on 2021-09-26 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210910_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_ended',
        ),
        migrations.AddField(
            model_name='event',
            name='event_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
