# Generated by Django 3.2.3 on 2021-10-07 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_day_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
