# Generated by Django 3.2.3 on 2021-11-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='event',
        ),
        migrations.DeleteModel(
            name='CarEvent',
        ),
    ]
