# Generated by Django 3.2.3 on 2021-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210919_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='daily_rental_cost',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
